algo = input('Digite algo: ')
print('Qual o tipo de {}: '.format(algo), type(algo))
print('{} Eh alfanumerico ? '.format(algo), algo.isalnum())
print('{} Eh um numero? '.format(algo), algo.isnumeric())
print('{} Eh alfabetico? '.format(algo), algo.isalpha())
print('{} Eh uma ascii? '.format(algo), algo.isascii())
print('{} Eh decimal? '.format(algo), algo.isdecimal())
print('{} Eh um digito? '.format(algo), algo.isdigit())
print('{} Eh um indetifier? '.format(algo), algo.isidentifier())
print('{} Eh uma letra minuscula? '.format(algo), algo.islower())
print('{} Eh printavel? '.format(algo), algo.isprintable())
print('{} Tem espaco? '.format(algo), algo.isspace())
print('{} Eh uma palavra capitalizada? '.format(algo), algo.istitle())
print('{} Eh uma letra maiscula? '.format(algo), algo.isupper())