algo = input('Escreva algo: ')
print(type(algo))
print(algo.isalnum())
print(algo.isnumeric())
print(algo.isalpha())
print(algo.isascii())
print(algo.isdecimal())
print(algo.isdigit())
print(algo.isidentifier())
print(algo.islower())
print(algo.isprintable())
print(algo.isspace())
print(algo.istitle())
print(algo.isupper())